### ISSUE TITLE
Channel not Responding

### ISSUE THREAD

**Issue by dyuser** [meriko/RoosterTeeth.bundle#10]
Any thought on the inability to watch any video?

**Comment by meriko** [comment]
The premium part is not working(see other issues). I just tried an episode of Red vs Blue + some more, they all worked for me? Which branch are you using?

**Comment by dyuser** [comment]
Main

**Comment by meriko** [comment]
Can you upload a log? com.plexapp.plugins.roosterteeth.log

**Comment by spaz926** [comment]
It looks like I am still logged in even after disabling login, not sure if that is what is causing the issue. Here is the com.plexapp.plugins.roosterteeth.log:

> 2017-02-13 01:50:04,288 (70000d7cd000) :  DEBUG (runtime:49) - Received packed state data (1432 bytes)
> 2017-02-13 01:50:04,297 (70000d7cd000) :  DEBUG (runtime:814) - Found route matching /video/roosterteeth/EpisodeCategories
> 2017-02-13 01:50:04,305 (70000d7cd000) :  DEBUG (networking:166) - Requesting 'http://roosterteeth.com/show/captain-dynamic'
> 2017-02-13 01:50:05,019 (70000d7cd000) :  DEBUG (networking:161) - Fetching 'http://roosterteeth.com/show/captain-dynamic' from the HTTP cache
> 2017-02-13 01:50:05,115 (70000d7cd000) :  DEBUG (services:616) - Found a service matching 'http://roosterteeth.com/episode/captain-dynamic-season-1-outtakes' - Rooster Teeth (com.plexapp.plugins.roosterteeth)
> 2017-02-13 01:50:05,116 (70000d7cd000) :  DEBUG (services:41) - Loading service code for Rooster Teeth (URLServiceRecord)
> 2017-02-13 01:50:05,925 (70000d7cd000) :  DEBUG (runtime:49) - Received packed state data (1432 bytes)
> 2017-02-13 01:50:05,929 (70000d7cd000) :  DEBUG (services:41) - Loading service code for Fallback (URLServiceRecord)
> 2017-02-13 01:50:07,100 (70000d7cd000) :  DEBUG (runtime:49) - Received packed state data (1432 bytes)
> 2017-02-13 01:50:07,105 (70000d7cd000) :  DEBUG (runtime:49) - Received packed state data (1432 bytes)
> 2017-02-13 01:50:07,108 (70000d7cd000) :  WARNING (objectkit:208) - Media part has no streams - attempting to synthesize
> 2017-02-13 01:50:07,112 (70000d7cd000) :  DEBUG (services:616) - Found a service matching 'http://roosterteeth.com/episode/captain-dynamic-season-1-episode-3' - Rooster Teeth (com.plexapp.plugins.roosterteeth)
> 2017-02-13 01:50:07,114 (70000d7cd000) :  DEBUG (runtime:49) - Received packed state data (1432 bytes)
> 2017-02-13 01:50:07,116 (70000d7cd000) :  DEBUG (runtime:49) - Received packed state data (1432 bytes)
> 2017-02-13 01:50:07,120 (70000d7cd000) :  DEBUG (runtime:49) - Received packed state data (1432 bytes)
> 2017-02-13 01:50:07,124 (70000d7cd000) :  DEBUG (services:616) - Found a service matching 'http://roosterteeth.com/episode/captain-dynamic-season-1-episode-2' - Rooster Teeth (com.plexapp.plugins.roosterteeth)
> 2017-02-13 01:50:07,126 (70000d7cd000) :  DEBUG (runtime:49) - Received packed state data (1432 bytes)
> 2017-02-13 01:50:07,130 (70000d7cd000) :  DEBUG (runtime:49) - Received packed state data (1432 bytes)
> 2017-02-13 01:50:07,133 (70000d7cd000) :  DEBUG (runtime:49) - Received packed state data (1432 bytes)
> 2017-02-13 01:50:07,137 (70000d7cd000) :  DEBUG (services:616) - Found a service matching 'http://roosterteeth.com/episode/captain-dynamic-season-1-episode-1' - Rooster Teeth (com.plexapp.plugins.roosterteeth)
> 2017-02-13 01:50:07,139 (70000d7cd000) :  DEBUG (runtime:49) - Received packed state data (1432 bytes)
> 2017-02-13 01:50:07,142 (70000d7cd000) :  DEBUG (runtime:49) - Received packed state data (1432 bytes)
> 2017-02-13 01:50:07,291 (70000d7cd000) :  DEBUG (runtime:49) - Received packed state data (1432 bytes)
> 2017-02-13 01:50:07,298 (70000d7cd000) :  DEBUG (runtime:88) - Sending packed state data (1465 bytes)
> 2017-02-13 01:50:07,299 (70000d7cd000) :  DEBUG (runtime:924) - Response: [200] MediaContainer, 6520 bytes

And here is the Plex Media Server.log:

> Feb 13, 2017 01:52:34.762 [0x700009d8b000] DEBUG - Beginning read from two-way stream.
> Feb 13, 2017 01:52:54.772 [0x70000a120000] ERROR - handle_stream_read error 2 End of file
> Feb 13, 2017 01:52:54.912 [0x70000a120000] DEBUG - Auth: We found auth token (xxxxxxxxxxxxxxxxxxxx), enabling token-based authentication.
> Feb 13, 2017 01:52:54.912 [0x70000a120000] DEBUG - Auth: authenticated user 1 as spaz926
> Feb 13, 2017 01:52:54.913 [0x70000a120000] DEBUG - Auth: Came in with a super-token, authorization succeeded.
> Feb 13, 2017 01:52:54.913 [0x70000a1a3000] DEBUG - Request: [::ffff:127.0.0.1:49221 (Loopback)] GET /player/proxy/poll?deviceClass=pc&protocolVersion=1&protocolCapabilities=timeline%2Cplayback%2Cnavigation%2Cmirror%2Cplayqueues&timeout=1 (4 live) GZIP Signed-in Token (spaz926)
> Feb 13, 2017 01:52:54.915 [0x70000a1a3000] DEBUG - Beginning read from two-way stream.
> Feb 13, 2017 01:53:14.919 [0x70000a09d000] ERROR - handle_stream_read error 2 End of file
> Feb 13, 2017 01:53:15.025 [0x70000a09d000] DEBUG - Auth: We found auth token (xxxxxxxxxxxxxxxxxxxx), enabling token-based authentication.
> Feb 13, 2017 01:53:15.026 [0x70000a09d000] DEBUG - Auth: authenticated user 1 as spaz926
> Feb 13, 2017 01:53:15.026 [0x70000a09d000] DEBUG - Auth: Came in with a super-token, authorization succeeded.
> Feb 13, 2017 01:53:15.026 [0x70000a226000] DEBUG - Request: [::ffff:127.0.0.1:49224 (Loopback)] GET /player/proxy/poll?deviceClass=pc&protocolVersion=1&protocolCapabilities=timeline%2Cplayback%2Cnavigation%2Cmirror%2Cplayqueues&timeout=1 (4 live) GZIP Signed-in Token (spaz926)

**Comment by spaz926** [comment]
So it seems to be an issue when login is enabled.

When login is not enabled it will play videos not locked for FIRST members.

**Comment by G0ldf1sh137** [comment]
Installed this channel today and had this issue. Confirming partial workaround from @spaz926.  When Enable Login is checked, only free content from RT seems to be available.  AH and all other channels will return the "Channel not Responding" error with the box checked.  Unchecking the box will properly load free content for all channels, however videos for FIRST members still return the error.

My log shows the same error listed in #6 I can upload a log if you would like, but the main issue is:
>CRITICAL (sandbox:298) - Function named 'ValidatePrefs' couldn't be found in the current environment

I think that there is an issue with reading in the username/password to generate the token to authenticate the user, and could be related to the other channels showing no content when the box is checked.

**Comment by meriko** [comment]
Should be fixed in latest, please confirm(thanks @sander1 and @smilligan93)

**Comment by G0ldf1sh137** [comment]
I uninstalled the bundle by @smilligan93 and tried to reinstall this one through the unofficial app store to test this one, but I still had channel not responding issues.  I also tried installing the bundle manually, and still see the same issue. After sending username/password, logs show the following error:

> 2017-05-15 21:07:51,911 (7f32097fa700) : DEBUG (runtime:717) - Handling request GET /:/plugins/com.plexapp.plugins.roosterteeth/prefs/set?login=true&username=XXXXX&password=YYYYY
> 2017-05-15 21:07:51,912 (7f32097fa700) : DEBUG (runtime:814) - Found route matching /:/plugins/com.plexapp.plugins.roosterteeth/prefs/set
> 2017-05-15 21:07:51,912 (7f32097fa700) : DEBUG (preferences:198) - Saved the user preferences
> 2017-05-15 21:07:51,913 (7f32097fa700) : CRITICAL (sandbox:303) - Exception when calling function 'ValidatePrefs' (most recent call last):
> File "/usr/lib/plexmediaserver/Resources/Plug-ins-995f1dead/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/sandbox.py", line 294, in call_named_function
> result = f(*args, **kwargs)
> File "/config/Library/Application Support/Plex Media Server/Plug-ins/RoosterTeeth.bundle/Contents/Code/__init__.py", line 58, in ValidatePrefs
> result = Login()
> NameError: global name 'Login' is not defined

I'm guessing either there was a commit missing from the pull request, or an issue with merge conflicts, but the version from @smilligan93 is still working for me if you need to find the diff.

**Comment by sander1** [comment]
Did you restart Plex Media Server after installing the new bundle?

**Comment by meriko** [comment]
Just pushed an update

**Comment by shadshack** [comment]
Getting this issue still. I'm able to play any free content, but trying to play any First-Only content gets the "Channel not Responding" error.
